NUM_GPUS: 1
DATASET:
  CROP_SIZE: 321
  SCALE_FROM: 0.9
  SCALE_TO: 1.0
TRAIN:
  BATCH_SIZE: 16
  NUM_EPOCHS: 24
  NUM_WORKERS: 8
  PRETRAIN: 5
NET:
  BACKBONE: "resnet38"
  MODEL: "ae"
  PRE_WEIGHTS_PATH: "./models/weights/ilsvrc-cls_rna-a1_cls1000_ep-0001.pth"
  LR: 0.001
  OPT: "SGD"
  LOSS: "SoftMargin"
  WEIGHT_DECAY: 0.0005
  PAMR_ITER: 10
  FOCAL_LAMBDA: 0.01
  FOCAL_P: 3
  SG_PSI: 0.3
TEST:
  METHOD: "multiscale"
  DATA_ROOT: "/fastdata/naraslanov"
  FLIP: True
  BATCH_SIZE: 8 # 4 scales, +1 flip for each
  PAD_SIZE: [1024, 1024]
  SCALES: [1, 0.5, 1.5, 2.0]
  FP_CUT_SCORE: 0.1
  BG_POW: 3
  USE_GT_LABELS: False
